target 'iosApp' do
  use_frameworks!
  platform :ios, '15.3'
  pod 'demo_app', :path => '../demo-app'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
